apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-recycle-config
  namespace: smart-recycle-dev
data:
  BACKEND_URL: "http://service-backend:8000"
  QDRANT_URL: "http://service-qdrant:6333"
  GPT_MODEL: "gpt-4o-mini-htw-test"
  EMBED_MODEL: "text-embedding-3-small-htw-test"
  COLLECTION: "abfall_docs"
  MIN_SCORE: "0.5"
  TOP_K: "1"