apiVersion: v1
kind: Secret
metadata:
  name: smart-recycle-secrets
  namespace: smart-recycle-dev
type: Opaque
stringData:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  AZURE_OPENAI_API_ENDPOINT: ${AZURE_OPENAI_API_ENDPOINT}
