apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: smart-recycle-dev
spec:
  selector:
    app: frontend-pod
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30085 
  type: NodePort
